// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMFpYcnj7GeJE9vZZri83kdmzgXN0wCZ4',
    appId: '1:133666874734:web:1520babde988265d958d7f',
    messagingSenderId: '133666874734',
    projectId: 'green-app-9a185',
    authDomain: 'green-app-9a185.firebaseapp.com',
    storageBucket: 'green-app-9a185.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkB-sEOGaNAsWD4QfOczw_5ik94137cXg',
    appId: '1:133666874734:android:74eae3246443db75958d7f',
    messagingSenderId: '133666874734',
    projectId: 'green-app-9a185',
    storageBucket: 'green-app-9a185.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3yIrBnlpl1G8pEuAoMAq1KECORber6Z0',
    appId: '1:133666874734:ios:5b425608bf4227fc958d7f',
    messagingSenderId: '133666874734',
    projectId: 'green-app-9a185',
    storageBucket: 'green-app-9a185.firebasestorage.app',
    iosBundleId: 'com.example.greenapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3yIrBnlpl1G8pEuAoMAq1KECORber6Z0',
    appId: '1:133666874734:ios:5b425608bf4227fc958d7f',
    messagingSenderId: '133666874734',
    projectId: 'green-app-9a185',
    storageBucket: 'green-app-9a185.firebasestorage.app',
    iosBundleId: 'com.example.greenapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMFpYcnj7GeJE9vZZri83kdmzgXN0wCZ4',
    appId: '1:133666874734:web:1ab81a97590089ae958d7f',
    messagingSenderId: '133666874734',
    projectId: 'green-app-9a185',
    authDomain: 'green-app-9a185.firebaseapp.com',
    storageBucket: 'green-app-9a185.firebasestorage.app',
  );
}
